import Head from 'next/head'
import Hero from '../components/Layout/Hero'
import Content from '../components/Layout/Content/Content'

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon A-Z Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Content/>
    </>
  )
}
